apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/gitsign?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cli
    appstudio.openshift.io/component: gitsign
    pipelines.appstudio.openshift.io/type: build
  name: gitsign-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.gitsign.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/securesign/gitsign:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  - name: go_unit_test
    value: "true"
  - name: go_test_command
    value: go test $(go list ./... | grep -v github.com/sigstore/gitsign/pkg/version)
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  - name: fips-check
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-multi-platform-oci-ta.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: run-unit-test
    stepSpecs:
    - computeResources:
        limits:
          memory: 4Gi
      name: run-tests
  taskRunTemplate:
    serviceAccountName: build-pipeline-gitsign
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
