apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/gitsign?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-1.3"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tas-tools-v1-3
    appstudio.openshift.io/component: gitsign-v1-3
    pipelines.appstudio.openshift.io/type: build
  name: gitsign-v1-3-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: release-version
    value: 1.3.2
  - name: dockerfile
    value: Dockerfile.gitsign.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/securesign/gitsign:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  - name: go_unit_test
    value: "true"
  - name: go_test_command
    value: go test $(go list ./... | grep -v github.com/sigstore/gitsign/pkg/version)
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: run-unit-test
    stepSpecs:
    - computeResources:
        limits:
          memory: 5Gi
      name: run-tests
    podTemplate:
      imagePullSecrets:
      - name: brew-registry-pull-secret
    serviceAccountName: build-pipeline-gitsign-v1-3
  taskRunTemplate:
    serviceAccountName: build-pipeline-gitsign-v1-3
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
